sawyer:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  right_j0_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_j0
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_j1_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_j1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_j2_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_j2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_j3_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_j3
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_j4_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_j4
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_j5_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_j5
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_j6_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_j6
    pid: {p: 100.0, i: 0.01, d: 10.0}
#  right_wrist_position_controller:
#    type: effort_controllers/JointPositionController
#    joint: right_wrist
#    pid: {p: 100.0, i: 0.01, d: 10.0}
#  right_j1_2_position_controller:
#    type: effort_controllers/JointPositionController
#    joint: right_j1_2
#    pid: {p: 100.0, i: 0.01, d: 10.0}
#  right_j2-2_position_controller:
#    type: effort_controllers/JointPositionController
#    joint: right_j2-2
#    pid: {p: 100.0, i: 0.01, d: 10.0}
#  right_j4-2_position_controller:
#    type: effort_controllers/JointPositionController
#    joint: right_j4-2
#    pid: {p: 100.0, i: 0.01, d: 10.0}