sawyer:
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50
  arm_position_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - right_j0
      - right_j1
      - right_j2
      - right_j3
      - right_j4
      - right_j5
      - right_j6